### ISSUE TITLE
Lance is too strooooooong

### ISSUE THREAD

**Issue by Alx-Lai** [john0312/hitcon-pcb-badge#154]

**Comment by ktpss95112** [comment]
I'm willing to give out my heart and liver.

**Comment by chuanchan1116** [comment]
<(_ _)>

**Comment by lisasasasa** [comment]
So Coooooooooooooooooooool

**Comment by justinlin099** [comment]
Lua

Alex Lai ***@***.***> 於 2024年8月18日 週日 下午5:34 寫道：

**Comment by doraeric** [comment]
![tuzki](https://media1.tenor.com/m/Tyryjt1i9J8AAAAC/tuzki-stickers.gif)

**Comment by ktpss95112** [comment]
Lance is tuuuuuzki
![](https://i.pinimg.com/originals/52/e4/2f/52e42f1a0410d1db856ed4f5a50dc5b0.gif)
