### ISSUE TITLE
surprise_msg never used

### ISSUE THREAD

**Issue by L4ys** [john0312/hitcon-pcb-badge#162]
The `surprise_msg` set in `ShowNameApp::SetSurpriseMsg` seems to never be used
Is this intentional?

https://github.com/john0312/hitcon-pcb-badge/blob/d445c370500e525b9b0a27a9922105ca2452e627/fw/Core/Hitcon/App/ShowNameApp.cc#L171-L178

**Comment by john0312** [comment]
Originally we want to allow the sender to control the surprise message while the sender can be modified to send different message, but we forgot to plumb it through on the receiver side. We only found out after flashing all 1500pcs.

**Comment by john0312** [comment]
Note that this bug has been fixed in the better-secret branch and is active in the base stations in our conference venue, but not active anywhere else.

**Comment by Alx-Lai** [comment]
Close as solved in latest version
